# Generated by Django 5.0.6 on 2024-06-19 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Painter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_artist",
                    models.CharField(max_length=50, verbose_name="Имя"),
                ),
                (
                    "lastname_artist",
                    models.CharField(max_length=50, verbose_name="Фамилия"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "мужчина"),
                            ("female", "женщина"),
                            ("other", "другое"),
                        ],
                        max_length=50,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "date_of_birth",
                    models.DateTimeField(
                        null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "city_of_birth",
                    models.CharField(
                        max_length=100, verbose_name="Город рождения"
                    ),
                ),
                (
                    "сity_of_residence",
                    models.CharField(
                        max_length=100, verbose_name="Город проживания"
                    ),
                ),
                (
                    "education",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Образование",
                    ),
                ),
                (
                    "art_education",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Художественное образование",
                    ),
                ),
                (
                    "teaching_experience",
                    models.CharField(
                        choices=[("yes", "да"), ("no", "нет")],
                        max_length=10,
                        verbose_name="Опыт преподавания",
                    ),
                ),
                (
                    "personal_style",
                    models.CharField(
                        choices=[("yes", "да"), ("no", "нет")],
                        max_length=10,
                        verbose_name="Индивидуальный стиль",
                    ),
                ),
                (
                    "solo_shows",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Информация о сольных выставках",
                    ),
                ),
                (
                    "solo_shows_gallery",
                    models.TextField(
                        blank=True, null=True, verbose_name="Сольные галереи"
                    ),
                ),
                (
                    "group_shows",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Информация о групповых галереях",
                    ),
                ),
                (
                    "group_shows_gallery",
                    models.TextField(
                        blank=True, null=True, verbose_name="Групповые галереи"
                    ),
                ),
                (
                    "group_shows_artist",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Другие художники в групповых галереях",
                    ),
                ),
                (
                    "collected_by_private_collectors",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Коллекционеры которые собирали работы художника",
                    ),
                ),
                (
                    "collected_by_major_institutions",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Крупные учреждения",
                    ),
                ),
                (
                    "industry_award",
                    models.TextField(
                        blank=True, null=True, verbose_name="Награды"
                    ),
                ),
                (
                    "social",
                    models.URLField(
                        blank=True, default="", verbose_name="Соц.сети"
                    ),
                ),
            ],
            options={
                "verbose_name": "художник",
                "verbose_name_plural": "художники",
                "ordering": ["-date_of_birth"],
            },
        ),
        migrations.CreateModel(
            name="ProductCard",
            fields=[
                (
                    "id_card_product",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("id_moderator_comment", models.IntegerField()),
                (
                    "foto",
                    models.ImageField(
                        upload_to="product_images/", verbose_name="Фото"
                    ),
                ),
                (
                    "width_painting",
                    models.FloatField(verbose_name="ширина картины"),
                ),
                (
                    "heigth_painting",
                    models.FloatField(verbose_name="высота картины"),
                ),
                (
                    "type",
                    models.CharField(
                        max_length=100,
                        verbose_name="Тип произведения искусства",
                    ),
                ),
                (
                    "genre",
                    models.CharField(max_length=100, verbose_name="Жанр"),
                ),
                (
                    "style",
                    models.CharField(max_length=100, verbose_name="Стиль"),
                ),
                (
                    "material_painting",
                    models.CharField(max_length=100, verbose_name="Материал"),
                ),
                (
                    "material_tablet",
                    models.CharField(
                        max_length=100, verbose_name="Материал подложки"
                    ),
                ),
                (
                    "painting_data_create",
                    models.DateField(verbose_name="Год создания картины"),
                ),
                (
                    "avg_cost_of_work",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Средняя стоимость работы",
                    ),
                ),
                (
                    "desired_selling_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Желаемая цена продажи",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artworks",
                        to="products.painter",
                        verbose_name="художник",
                    ),
                ),
            ],
            options={
                "verbose_name": "карточка товара",
                "verbose_name_plural": "карточки товаров",
                "ordering": ["-id_card_product"],
            },
        ),
    ]
