# Generated by Django 5.0.6 on 2024-06-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="painter",
            name="date_of_birth",
            field=models.DateField(verbose_name="Дата рождения"),
        ),
    ]
