# Generated by Django 5.0.6 on 2024-07-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0002_rename_material_painting_productcard_material_work_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="country",
            field=models.CharField(
                default=0, max_length=100, verbose_name="Страна рождения"
            ),
            preserve_default=False,
        ),
    ]
