# Generated by Django 5.0.6 on 2024-06-28 21:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_painter_date_of_birth"),
        ("products", "0002_alter_productcard_options_and_more"),
    ]

    operations = []
