# Generated by Django 5.0.6 on 2024-07-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_artist_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="exhibition",
            name="city",
            field=models.CharField(
                default=0, max_length=100, verbose_name="Город"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="exhibition",
            name="country",
            field=models.CharField(
                default=0, max_length=100, verbose_name="Страна"
            ),
            preserve_default=False,
        ),
    ]
