# Generated by Django 5.0.6 on 2024-06-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_id_seller"),
        ("products", "0004_artist_exhibition_and_more"),
        ("users", "0004_alter_customuser_favorite_artist"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Painter",
        ),
        migrations.AddField(
            model_name="artist",
            name="group_shows",
            field=models.ManyToManyField(
                blank=True,
                related_name="artists",
                to="products.groupshow",
                verbose_name="информация о групповых галереях",
            ),
        ),
        migrations.AddField(
            model_name="artist",
            name="solo_shows",
            field=models.ManyToManyField(
                blank=True,
                related_name="artists",
                to="products.soloshow",
                verbose_name="информация о сольных выставках",
            ),
        ),
    ]
