# Generated by Django 5.0.6 on 2024-07-01 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_rename_сity_of_residence_artist_city_of_residence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={},
        ),
        migrations.RemoveField(
            model_name="bid",
            name="price",
        ),
        migrations.RemoveField(
            model_name="bid",
            name="product_card",
        ),
        migrations.AddField(
            model_name="bid",
            name="age",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Возраст художника"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="artist_lastname",
            field=models.CharField(
                default=1, max_length=50, verbose_name="Фамилия художника"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="artist_name",
            field=models.CharField(
                default=1, max_length=50, verbose_name="Имя художника"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="count_artist",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Количество вхождений имени художника"
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="count_title",
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name="Количество вхождений названия"
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="country",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Страна рождения"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="gender",
            field=models.CharField(
                choices=[
                    ("male", "мужчина"),
                    ("female", "женщина"),
                    ("other", "другое"),
                ],
                default=1,
                max_length=50,
                verbose_name="Пол",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="group_shows",
            field=models.ManyToManyField(
                blank=True,
                related_name="bids",
                to="products.groupshow",
                verbose_name="Информация о групповых выставках",
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="height",
            field=models.FloatField(default=1, verbose_name="Высота картины"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="is_alive",
            field=models.BooleanField(default=True, verbose_name="Живет"),
        ),
        migrations.AddField(
            model_name="bid",
            name="material_tablet",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Материал подложки"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="material_work",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Материал"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="photo",
            field=models.ImageField(
                null=True, upload_to="product_images/", verbose_name="Фото"
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="solo_shows",
            field=models.ManyToManyField(
                blank=True,
                related_name="bids",
                to="products.soloshow",
                verbose_name="Информация о сольных выставках",
            ),
        ),
        migrations.AddField(
            model_name="bid",
            name="title",
            field=models.CharField(
                default=0, max_length=100, verbose_name="Название"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="width",
            field=models.FloatField(default=1, verbose_name="Ширина картины"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="year_create",
            field=models.PositiveSmallIntegerField(
                default=1, verbose_name="Год создания картины"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bid",
            name="сity_of_residence",
            field=models.CharField(
                default=1, max_length=100, verbose_name="Город проживания"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="exhibition",
            name="year",
            field=models.PositiveSmallIntegerField(verbose_name="Год"),
        ),
        migrations.AlterField(
            model_name="productcard",
            name="year_create",
            field=models.PositiveSmallIntegerField(
                verbose_name="Год создания картины"
            ),
        ),
    ]
