# Generated by Django 5.0.6 on 2024-07-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_alter_bid_options_remove_bid_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bid",
            options={
                "ordering": ["-id"],
                "verbose_name": "заявка",
                "verbose_name_plural": "заявки",
            },
        ),
        migrations.AddField(
            model_name="bid",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Прогнозируемая цена",
            ),
        ),
    ]
