# Generated by Django 5.0.6 on 2024-07-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_remove_bid_сity_of_residence"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="group_shows",
        ),
        migrations.RemoveField(
            model_name="bid",
            name="solo_shows",
        ),
        migrations.AddField(
            model_name="bid",
            name="solo_shows",
            field=models.CharField(
                default=1,
                max_length=100,
                verbose_name="Информация о групповых выставках",
            ),
            preserve_default=False,
        ),
    ]
