# Generated by Django 5.0.6 on 2024-07-02 10:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0009_remove_bid_group_shows_remove_bid_solo_shows_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="name_category",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="style",
            old_name="name_style",
            new_name="name",
        ),
    ]
