# Generated by Django 5.0.6 on 2024-07-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_bid_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bid",
            name="count_artist",
            field=models.PositiveSmallIntegerField(
                verbose_name="Количество вхождений имени художника"
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="count_title",
            field=models.PositiveSmallIntegerField(
                verbose_name="Количество вхождений названия"
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="is_alive",
            field=models.BooleanField(verbose_name="Живет"),
        ),
    ]
