# Generated by Django 5.0.6 on 2024-07-02 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "products",
            "0013_alter_bid_count_artist_alter_bid_count_title_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcard",
            name="desired_price",
        ),
    ]
