# Generated by Django 5.0.6 on 2024-07-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_rename_heigth_productcard_height"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="bio",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Биография"
            ),
        ),
        migrations.AlterField(
            model_name="productcard",
            name="description",
            field=models.TextField(max_length=500, verbose_name="Описание"),
        ),
    ]
