name: sagaart-2

services:
  sagaart2-db:
    image: postgres:latest
    container_name: sagaart2-db
    env_file:
      - ../.env
    restart: on-failure
    volumes:
      - db_data:/var/lib/postgresql/data/

  backend:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py createsuperuser --no-input || true &&
             python manage.py collectstatic --no-input --clear &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - backend_static:/app/static/
      - backend_media:/app/media/
    depends_on:
      - sagaart2-db

  frontend:
    image: username/image_name:latest
    container_name: frontend
    volumes:
      - frontend_static:/app/build

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    environment:
      - NGINX_PORT=80
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - backend_static:/var/html/static
      - backend_media:/var/html/media
    depends_on:
      - backend
      - frontend

volumes:
  db_data:
  backend_static:
  backend_media:
  frontend_static:
