# Generated by Django 5.0.6 on 2024-06-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_productcard_options_and_more"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="favorite_category",
            field=models.ManyToManyField(
                related_name="users_like",
                to="products.category",
                verbose_name="Любимые категории",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="favorite_style",
            field=models.ManyToManyField(
                related_name="users_like",
                to="products.style",
                verbose_name="Любимые стили",
            ),
        ),
    ]
