# Generated by Django 5.0.6 on 2024-06-26 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        ("users", "0002_customuser_favorite_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="favorite_artist",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_like",
                to="products.painter",
                verbose_name="Любимые художники",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="favorite_category",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_like",
                to="products.category",
                verbose_name="Любимые категории",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="favorite_style",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_like",
                to="products.style",
                verbose_name="Любимые стили",
            ),
        ),
    ]
