# Generated by Django 5.0.6 on 2024-06-28 21:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_artist_exhibition_and_more"),
        ("users", "0003_alter_customuser_favorite_artist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="favorite_artist",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_like",
                to="products.artist",
                verbose_name="Любимые художники",
            ),
        ),
    ]
